### ISSUE TITLE
Run visual regression against a custom Selenium/PhantomJS instance

### ISSUE THREAD

**Issue by mccrodp** [shoov/shoov#376]
Hey,

I have successfully ran visual regression testing via PhantomJS locally. Question is, can I do this via `app.shoov.io` in anyway, pointing it to say a (dockerized) PhantomJS instance in the cloud?

I see that the `behat.local.yml.example` config shows a commented out config for pointing to a Selenium docker container. Is this something we can leverage on `app.shoov.io` and locally?

I have successfully configured a Selenium Grid by following this article: http://testdetective.com/selenium-grid-with-docker/ Not so sure on the other hand how to make our visual regression tests run against it.

I updated the the behat yml to the below, but don't think it is run via `mocha` command when in the visual-monitor directory.

````yml
  ## Selenium integration
  selenium2:
    # http://selenium is the URL alias to the Selenium docker container.
    wd_host: "http://localhost:4444/wd/hub"
    browser: chrome
````

Any ideas? Thanks!

````
1) Visual monitor testing "before all" hook:
     RuntimeError
     (UnknownError:13) An unknown server-side error occurred while processing the command.
     Problem: Error forwarding the new session cannot find : Capabilities [{rotatable=true, locationContextEnabled=true, browserName=phantomjs, javascriptEnabled=true, handlesAlerts=true, version=, platform=ANY, requestOrigins={name=webdriverio, version=2.4.5, url=http://webdriver.io}}]

     Callstack:
     -> init()
````

It seems to be looking for `browserName=phantomjs`, so I guess looking for a method to indicate that we are looking for Selenium via the custom URL.
